apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p46
  namespace: p46-beamline
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: p46-beamline
  destination:
    name: argus
    namespace: p46-beamline
  source:
    path: apps
    repoURL: https://github.com/epics-containers/p46-deployment
    targetRevision: add-authn
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
